USE CK2022_2023

CREATE DATABASE CK2022_2023

CREATE TABLE KHACHHANG (
    MAKH INT PRIMARY KEY,
    TENKH VARCHAR(255),
    NGAYSINH DATE,
    DIACHI VARCHAR(255),
    CMND VARCHAR(12)
);

CREATE TABLE LOAICH (
    MALCH INT PRIMARY KEY,
    TENLCH VARCHAR(255),
    NHOMCC VARCHAR(255)
);

CREATE TABLE CANHO (
    MACH INT PRIMARY KEY,
    TENCH VARCHAR(255),
    MALCH INT,
    DIENTICH FLOAT,
    VITRI VARCHAR(255),
    SOPHONG INT,
    GIA FLOAT,
    FOREIGN KEY (MALCH) REFERENCES LOAICH(MALCH)
);

CREATE TABLE HINHTHUCTG (
    MAHT INT PRIMARY KEY,
    TENHT VARCHAR(255),
    PHANTRAMTT FLOAT,
    LAISUAT FLOAT,
    KYHAN INT
);

CREATE TABLE TRAGOP (
    MATG INT PRIMARY KEY,
    MACH INT,
    MAKH INT,
    MAHT INT,
    NGAYMUA DATE,
    SOTIENTT FLOAT,
    FOREIGN KEY (MACH) REFERENCES CANHO(MACH),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MAHT) REFERENCES HINHTHUCTG(MAHT)
);

--DE 1
--a. Tìm thông tin những khách hàng (MAKH, TENKH, DIACHI) có năm sinh từ 1980 đến
--1985 đã mua trả góp căn hộ vào ngày ‘1/2/2023’ (NGAYMUA).
SELECT MAKH, TENKH, DIACHI 
FROM KHACHHANG KH JOIN TRAGOP TG ON KH.MAKH = TG.MAKH
WHERE YEAR(NGAYSINH) BETWEEN 1980 AND 1985
AND NGAYMUA = '20230201'

--b. Liệt kê thông tin các khách hàng (TENKH, DIACHI) mua trả góp căn hộ có diện tích trên
--80m2. Kết quả xuất ra theo tên khách hàng có thứ tự giảm dần. (1đ)
SELECT TENKH, DIACHI
FROM KHACHHANG KH JOIN TRAGOP TG ON KH.MAKH = TG.MAKH
JOIN CANHO CH ON CH.MACH = TG.MACH
WHERE DIENTICH > 80
ORDER BY TENKH DESC

--c. Liệt kê mã loại căn hộ (MALCH), tên loại căn hộ (TENLCH) và số lượng căn hộ trong
--từng loại căn hộ. (1đ)
SELECT LOAICH.MALCH, TENLCH, COUNT(MACH) AS SLCANHO
FROM LOAICH JOIN CANHO ON LOAICH.MALCH = CANHO.MALCH
GROUP BY LOAICH.MALCH, TENLCH

--d. Cho biết khách hàng (MAKH, TENKH) đang trả góp nhóm chung cư (NHOMCC) ‘cao
--cấp’ nhưng không trả góp nhóm chung cư ‘trung cấp’. (1đ)
SELECT KH.MAKH, TENKH
FROM KHACHHANG KH 
JOIN TRAGOP TG ON KH.MAKH = TG.MAKH
JOIN CANHO CH ON TG.MACH = CH.MACH
JOIN LOAICH LC ON CH.MALCH = LC.MALCH
WHERE LC.NHOMCC = 'cao cap'
EXCEPT
SELECT KH.MAKH, TENKH
FROM KHACHHANG KH 
JOIN TRAGOP TG ON KH.MAKH = TG.MAKH
JOIN CANHO CH ON TG.MACH = CH.MACH
JOIN LOAICH LC ON CH.MALCH = LC.MALCH
WHERE LC.NHOMCC = 'trung cap'

--e. Tìm khách hàng (TENKH) đã mua trả góp tất cả các căn hộ loại ‘penthouse’ của nhóm
--chung cư ‘cao cấp’. (1đ)
SELECT TENKH FROM KHACHHANG WHERE NOT EXISTS
	(SELECT * FROM CANHO JOIN LOAICH ON CANHO.MALCH = LOAICH.MALCH
	WHERE TENLCH = 'penthouse' AND NHOMCC = 'cao cap'
	AND NOT EXISTS 
		(SELECT * FROM TRAGOP WHERE TRAGOP.MAKH = KHACHHANG.MAKH AND TRAGOP.MACH = CANHO.MACH))

--f. Trong năm 2022, loại căn hộ nào (MALCH, TENLCH) thuộc nhóm chung cư 'cao cấp' có
--số lượt bán trả góp nhiều hơn 10.
SELECT LC.MALCH, LC.TENLCH
FROM LOAICH LC
JOIN CANHO CH ON LC.MALCH = CH.MALCH
JOIN TRAGOP TG ON CH.MACH = TG.MACH
WHERE LC.NHOMCC = 'cao cấp'
AND YEAR(TG.NGAYMUA) = 2022
GROUP BY LC.MALCH, LC.TENLCH
HAVING COUNT(TG.MATG) > 10;


--DE 2
--a. Tìm các căn hộ (MACH, TENCH) thuộc loại ‘shophouse’ (TENLCH) có giá bán (GIA) từ
--1.500.000 đồng đến 2.000.000 đồng. (1đ)
SELECT MACH, TENCH
FROM CANHO JOIN LOAICH ON CANHO.MALCH = LOAICH.MALCH
WHERE TENLCH = 'shophouse'
AND GIA BETWEEN 1500000 AND 2000000

--b. Liệt kê những căn hộ (TENCH, MALCH) thực hiện trả góp trong kỳ hạn lớn hơn 120 tháng?
--Kết quả trả về sắp xếp theo thứ tự kỳ hạn giảm dần. (1đ)
SELECT TENCH, MALCH
FROM CANHO JOIN LOAICH ON CANHO.MALCH = LOAICH.MALCH
JOIN TRAGOP ON TRAGOP.MACH = CANHO.MACH
JOIN HINHTHUCTG HT ON HT.MAHT = TRAGOP.MAHT
WHERE KYHAN > 120
ORDER BY KYHAN DESC

--c. Liệt kê mã hình thức trả góp (MAHT), tên hình thức trả góp (TENHT) và số lượng căn hộ
--trả góp trong từng hình thức trả góp. (1đ)
SELECT HT.MAHT, TENHT, COUNT(MACH)
FROM HINHTHUCTG HT JOIN TRAGOP TG ON HT.MAHT = TG.MAHT
GROUP BY HT.MAHT, TENHT

--d. Cho biết khách hàng (MAKH, TENKH) đang trả góp tên loại căn hộ là (TENLCH)
--‘penthouse’ và tên loại căn hộ là ‘duplex’. (1đ)
SELECT KH.MAKH, TENKH
FROM KHACHHANG KH JOIN TRAGOP TG ON KH.MAKH = TG.MAKH
JOIN CANHO CH ON TG.MACH = CH.MACH
JOIN LOAICH LCH ON LCH.MALCH = CH.MALCH
WHERE TENLCH = 'penthouse'
UNION
SELECT KH.MAKH, TENKH
FROM KHACHHANG KH JOIN TRAGOP TG ON KH.MAKH = TG.MAKH
JOIN CANHO CH ON TG.MACH = CH.MACH
JOIN LOAICH LCH ON LCH.MALCH = CH.MALCH
WHERE TENLCH = 'dulex'

--e. Tìm khách hàng (TENKH) đã mua trả góp tất cả các căn hộ loại duplex của nhóm chung cư
--cao cấp. (1đ)
SELECT TENKH FROM KHACHHANG WHERE NOT EXISTS
	(SELECT * FROM CANHO CH JOIN LOAICH LCH ON LCH.MALCH = CH.MALCH
	WHERE TENLCH = 'duplex' AND NHOMCC = 'cao cap'
	AND NOT EXISTS
		(SELECT * FROM TRAGOP WHERE TRAGOP.MACH = CANHO.MACH AND TRAGOP.MAKH = KHACHHANG.MAKH))

--f. Trong năm 2019, khách hàng nào (MAKH, TENKH) có tổng tiền phải trả trước cho việc
--mua trả góp căn hộ 4 phòng là lớn hơn 900.000.000
SELECT KH.MAKH, KH.TENKH
FROM KHACHHANG KH
JOIN TRAGOP TG ON KH.MAKH = TG.MAKH
JOIN CANHO CH ON TG.MACH = CH.MACH
WHERE CH.SOPHONG = 4
AND YEAR(TG.NGAYMUA) = 2019
GROUP BY KH.MAKH, KH.TENKH
HAVING SUM(TG.SOTIENTT) > 900000000;


