USE CK2018_2019_DE2
CREATE DATABASE CK2018_2019_DE2

CREATE TABLE MATHANG (
    MAMH VARCHAR(20) PRIMARY KEY,
    TENMH VARCHAR(50),
    DVT VARCHAR(20),
    NUOCSX VARCHAR(50)
);

CREATE TABLE NHACC (
    MACC VARCHAR(20) PRIMARY KEY,
    TENCC VARCHAR(50),
    DIACHICC VARCHAR(100)
);

CREATE TABLE CUNGCAP (
    MACC VARCHAR(20),
    MAMH VARCHAR(20),
    TUNGAY DATE,
    PRIMARY KEY (MACC, MAMH),
    FOREIGN KEY (MACC) REFERENCES NHACC(MACC),
    FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)
);

CREATE TABLE DONDH (
    MADH VARCHAR(20) PRIMARY KEY,
    NGAYDH DATE,
    MACC VARCHAR(20),
    TRIGIA DECIMAL(15, 2) DEFAULT 0,
    SOMH INT DEFAULT 0,
    FOREIGN KEY (MACC) REFERENCES NHACC(MACC)
);

CREATE TABLE CHITIET (
    MADH VARCHAR(20),
    MAMH VARCHAR(20),
    SOLUONG INT,
    DONGIA DECIMAL(10, 2),
    THANHTIEN AS (SOLUONG * DONGIA),
    PRIMARY KEY (MADH, MAMH),
    FOREIGN KEY (MADH) REFERENCES DONDH(MADH),
    FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)
);

--ĐỀ 2
--Liệt kê danh sách các nhà cung cấp (MACC, TENCC, TUNGAY) có thể cung cấp mã mặt 
--hàng ‘MH0001’ từ ngày ‘1/1/2018’ trở về sau. (1 điểm)
SELECT NHACC.MACC, TENCC, TUNGAY
FROM NHACC JOIN CUNGCAP CC  ON NHACC.MACC = CC.MACC
WHERE MAMH = 'MH001' AND TUNGAY = '20180101'

--b. Tính tổng thành tiền của đơn đặt hàng có mã mặt hàng là ‘MH014’ từ nhà cung cấp có mã
--là ‘NCC007’. (1 điểm)
SELECT SUM(THANHTIEN)
FROM CHITIET CT JOIN CUNGCAP CC ON CT.MAMH=CC.MAMH
WHERE CT.MAMH = 'MH014'
AND MACC='NCC007'

--c. Liệt kê những nhà cung cấp (MACC, TENCC) có thể cung cấp những mặt hàng do ‘Mỹ’
--sản xuất mà không cung cấp những mặt hàng do ‘Hàn Quốc’ sản xuất. (1 điểm)
SELECT NHACC.MACC, TENCC
FROM NHACC JOIN CUNGCAP CC ON NHACC.MACC = CC.MACC
JOIN MATHANG ON MATHANG.MAMH = CC.MAMH
WHERE NUOCSX='My'
EXCEPT
SELECT NHACC.MACC, TENCC
FROM NHACC JOIN CUNGCAP CC ON NHACC.MACC = CC.MACC
JOIN MATHANG ON MATHANG.MAMH = CC.MAMH
WHERE NUOCSX='Han Quoc'

--d. Tính tổng trị giá của tất cả các đơn đặt hàng theo từng năm. Thông tin hiển thị: Năm đặt 
--hàng, Tổng trị giá. (1 điểm)
SELECT YEAR(NGAYDH), SUM(TRIGIA) AS TONGTRIGIA
FROM DONDH
GROUP BY YEAR(NGAYDH)

--e. Tìm những mã đơn đặt hàng (MADH) đã đặt tất cả các mặt hàng của nhà cung cấp có tên 
--‘Vinamilk’ (TENCC). (1 điểm)
SELECT MADH FROM DONDH WHERE NOT EXISTS
	(SELECT * 
	FROM MATHANG JOIN CUNGCAP CC ON CC.MAMH = MATHANG.MAMH 
	JOIN NHACC ON NHACC.MACC = CC.MACC
	WHERE TENCC = 'Vinamilk' 
	AND NOT EXISTS
		(SELECT * FROM CHITIET CT WHERE CT.MADH = DONDH.MADH AND CT.MAMH = MATHANG.MAMH))

--f. Tìm những mặt hàng (MAMH, TENMH) có số lượng đặt hàng ít nhất trong năm 2018. (1 
--điểm)
SELECT MH.MAMH, TENMH, MIN(TONGSOLUONG)
FROM MATHANG MH JOIN CHITIET CT ON MH.MAMH = CT.MAMH
JOIN DONDH DH ON CT.MADH = DH.MADH
JOIN 
	(SELECT MAMH, SUM(SOLUONG) AS TONGSOLUONG
	FROM CHITIET CT  JOIN DONDH DH ON CT.MADH = DH.MADH
	WHERE YEAR(NGAYDH)=2018
	GROUP BY MAMH) AS TONGSL
ON TONGSL.MAMH = MH.MAMH
