USE QLXN

CREATE DATABASE QLXN

--CAU 1.

CREATE TABLE NHACUNGCAP
(
	MANCC VARCHAR(10) NOT NULL,
	TENNCC VARCHAR(30),
	QUOCGIA VARCHAR(20),
	LOAINCC VARCHAR(20)
)

CREATE TABLE DUOCPHAM
(
	MADP VARCHAR(10) NOT NULL,
	TENDP VARCHAR(30),
	LOAIDP VARCHAR(20),
	GIA MONEY
)

CREATE TABLE PHIEUNHAP 
(
	SOPN VARCHAR(10) NOT NULL,
	NGNHAP SMALLDATETIME,
	MANCC VARCHAR(10),
	LOAINHAP VARCHAR(20)
)

CREATE TABLE CTPN
(	
	SOPN VARCHAR(10) NOT NULL,
	MADP VARCHAR(10) NOT NULL,
	SOLUONG INT
)
--KHOA CHINH
ALTER TABLE NHACUNGCAP ADD CONSTRAINT PK_NCC PRIMARY KEY (MANCC)
ALTER TABLE DUOCPHAM ADD CONSTRAINT PK_DP PRIMARY KEY (MADP)
ALTER TABLE PHIEUNHAP ADD CONSTRAINT PK_PN PRIMARY KEY (SOPN)
ALTER TABLE CTPN ADD CONSTRAINT PK_CTPN PRIMARY KEY (SOPN, MADP)

--KHOA NGOAII
ALTER TABLE PHIEUNHAP ADD CONSTRAINT FK_PN_MANCC FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP (MANCC)
ALTER TABLE CTPN ADD CONSTRAINT FK_CT_SOPN FOREIGN KEY (SOPN) REFERENCES PHIEUNHAP (SOPN)
ALTER TABLE CTPN ADD CONSTRAINT FK_CT_MADP FOREIGN KEY (MADP) REFERENCES DUOCPHAM (MADP)

--CAU 2.
INSERT INTO NHACUNGCAP (MANCC, TENNCC, QUOCGIA, LOAINCC) VALUES
('NCC01','Phuc Hung','Viet Nam','Thuong xuyen'),
('NCC02','J. B. Pharmaceuticals','India','Vang lai'),
('NCC03','Sapharco','Singapore','Vang lai')

INSERT INTO DUOCPHAM (MADP, TENDP, LOAIDP, GIA) VALUES
('DP01','Thuoc ho PH','Siro',120000),
('DP02','Zecud Herbal CouchRemedy','Vien nen',200000),
('DP03','Cotrim','Vien sui', 80000)

INSERT INTO PHIEUNHAP (SOPN, NGNHAP, MANCC, LOAINHAP) VALUES
('00001','20171122','NCC01','Noi dia'),
('00002','20171204','NCC03','Nhap khau'),
('00003','20171210','NCC02','Nhap khau')

INSERT INTO CTPN (SOPN, MADP, SOLUONG) VALUES
('00001','DP01',100),
('00002','DP02',200),
('00003','DP03',543)

--CAU 3.
ALTER TABLE DUOCPHAM ADD CONSTRAINT CHK_GIA CHECK ((LOAIDP = 'Siro' AND GIA >100000) OR (LOAIDP!= 'Siro'))

--CAU 4.
CREATE TRIGGER TRG_PHIEUNHAP
ON PHIEUNHAP
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @QUOCGIA VARCHAR(20), @LOAINHAP VARCHAR(20), @MANCC VARCHAR(10)
	SELECT @LOAINHAP = LOAINHAP, @MANCC = MANCC 
	FROM INSERTED
	SELECT @QUOCGIA = QUOCGIA
	FROM NHACUNGCAP
	WHERE @MANCC = MANCC
	IF (@QUOCGIA != 'Viet Nam' AND @LOAINHAP !='Nhap khau')
	BEGIN
		PRINT 'LOI PHIEUNHAP: SAI LOAI NHAP!'
		ROLLBACK TRANSACTION
	END
END

CREATE TRIGGER TRG_NHACC
ON NHACUNGCAP
FOR UPDATE
AS
BEGIN
	DECLARE @QUOCGIA VARCHAR(20), @LOAINHAP VARCHAR(20), @MANCC VARCHAR(10)
	SELECT @QUOCGIA = QUOCGIA
	FROM INSERTED
	SELECT @LOAINHAP = LOAINHAP,  @MANCC = MANCC
	FROM PHIEUNHAP
	IF (@QUOCGIA != 'Viet Nam' AND @LOAINHAP !='Nhap khau')
	BEGIN
		PRINT 'LOI NHACC: SAI QUOC GIA!'
		ROLLBACK TRANSACTION
	END
END

UPDATE NHACUNGCAP 
SET QUOCGIA =  'm'
WHERE MANCC ='NCC01'
SELECT * FROM NHACUNGCAP
--CAU 5.
SELECT * 
FROM PHIEUNHAP
WHERE MONTH(NGNHAP)=12 AND YEAR(NGNHAP)=2017
ORDER BY NGNHAP ASC

--CAU 6.
SELECT TOP 1 WITH TIES DP.MADP, TENDP, SUM(SOLUONG) SL
FROM DUOCPHAM DP JOIN CTPN CT ON DP.MADP = CT.MADP
GROUP BY DP.MADP, TENDP
ORDER BY SL DESC

--CAU 7.
SELECT DP.MADP, TENDP
FROM DUOCPHAM DP JOIN CTPN CT  ON  DP.MADP = CT.MADP
JOIN PHIEUNHAP PN ON PN.SOPN = CT.SOPN
JOIN NHACUNGCAP NCC ON NCC.MANCC = PN.MANCC
WHERE LOAINCC = 'Thuong xuyen'

--CAU 8
SELECT * FROM NHACUNGCAP WHERE NOT EXISTS
	(SELECT * FROM DUOCPHAM WHERE GIA > 100000 AND NOT EXISTS
		(SELECT * FROM CTPN JOIN PHIEUNHAP ON CTPN.SOPN = PHIEUNHAP.SOPN
					WHERE CTPN.MADP = DUOCPHAM.MADP AND PHIEUNHAP.MANCC = NHACUNGCAP.MANCC
							AND YEAR(NGNHAP)=2017))